name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  fetch_client: ^1.0.2
  get_it: ^7.7.0
  provider: ^6.1.2
  sqflite: ^2.3.3
  sqflite_common_ffi_web: '>=0.1.0-dev.1'
  dartz: ^0.10.1
  path: ^1.9.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  animated_text_kit: ^4.2.2
  path_provider: ^2.1.3
  logger: ^2.3.0
  internet_connection_checker_plus: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/mock_data/
    - lib/features/home/mock_distributors_data.json
    - lib/features/home/mock_recentActivity_data.json
    - lib/features/manage_money/cash_in_out/bank_account_details.json
    - lib/features/manage_money/choose_a_bank/choose_a_bank.json
    - lib/features/signup/select_phone_number/mock_mobile_info.json
    - lib/features/signup/user_info/mock_res.json
    - lib/features/signup/select_role/mock_company_info.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
